-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customers"
(
    "FullName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Phone" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default",
    "Address" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "BirthDate" date NOT NULL,
    "CustomerId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "IdDocument" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Customers_pkey" PRIMARY KEY ("CustomerId")
);

CREATE TABLE IF NOT EXISTS public."Invoices"
(
    "InvoiceId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CustomerId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "Subtotal" double precision NOT NULL,
    "Taxes" double precision NOT NULL,
    "Total" double precision NOT NULL,
    "PaymentMethodId" integer NOT NULL,
    CONSTRAINT "Invoices_pkey" PRIMARY KEY ("InvoiceId")
);

CREATE TABLE IF NOT EXISTS public."OrderItems"
(
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    "OrderId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Date" date NOT NULL,
    CONSTRAINT "Order_pkey" PRIMARY KEY ("OrderId")
);

CREATE TABLE IF NOT EXISTS public."PaymentMethods"
(
    "PaymentMethodId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PaymentMethods_pkey" PRIMARY KEY ("PaymentMethodId")
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    "ProductId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Price" double precision,
    CONSTRAINT "Products_pkey" PRIMARY KEY ("ProductId")
);

ALTER TABLE IF EXISTS public."Invoices"
    ADD CONSTRAINT customer FOREIGN KEY ("CustomerId")
    REFERENCES public."Customers" ("CustomerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Invoices"
    ADD CONSTRAINT "order" FOREIGN KEY ("OrderId")
    REFERENCES public."Orders" ("OrderId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Invoices"
    ADD CONSTRAINT "payment-method" FOREIGN KEY ("PaymentMethodId")
    REFERENCES public."PaymentMethods" ("PaymentMethodId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."OrderItems"
    ADD CONSTRAINT "order" FOREIGN KEY ("OrderId")
    REFERENCES public."Orders" ("OrderId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."OrderItems"
    ADD CONSTRAINT product FOREIGN KEY ("ProductId")
    REFERENCES public."Products" ("ProductId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;